### PR TITLE
feat: add a resource_class param to badass orb split & combine jobs.

### PR DESCRIPTION
**Pull request by jhillacre**

### CODE REVIEW

**Comment by jhillacre** [comment]
published as arrai/badass:9.2.0

**Comment by pmack** [comment]
This might be a dupe that's included in my pr as well.

**Comment by jhillacre** [comment]
ok, hopefully it merges clean.

**Review by pmack — APPROVED** [review]

**Comment by jhillacre** [comment]
yours is better

**Comment by jhillacre** [comment]
means I published a bad version of the badass orb, probably after you already published.
should make a new major tomorrow to clear that out.

**Comment by pmack** [comment]
Mine was published as 9.1.0. So yea, we should just bump to 10.0.0 and call it a day.

**Comment by jhillacre** [comment]
published `arrai/badass@10.0.0`.

**Pull request closed without merging**
